import os
from crewai import Agent, Task, Crew, Process, LLM

def run_legal_war_room(user_message, retrieved_laws):
    # --- 1. INITIALIZE THE BRAIN (NATIVE CREWAI) ---
    llm = LLM(
        model="groq/llama-3.3-70b-versatile",
        api_key=os.environ.get("GROQ_API_KEY"),
        temperature=0.0
    )

    # --- 2. HIRE THE VIRTUAL EMPLOYEES (AGENTS) ---
    
    researcher = Agent(
        role='Senior Legal Researcher',
        goal='Analyze the user complaint and extract ONLY the applicable laws from the provided database.',
        backstory='You are a meticulous paralegal. You never make up laws. You strictly rely on the provided database.',
        verbose=True,
        allow_delegation=False,
        llm=llm
    )

    defender = Agent(
        role='Ruthless Corporate Defense Attorney',
        goal='Find the legal loopholes the company will use to deny the consumer their rights.',
        backstory='You are a highly-paid corporate lawyer for the opposing company. Your job is to find excuses like "It was a system glitch", "The 7-day policy expired", or "We are just a third-party platform".',
        verbose=True,
        allow_delegation=False,
        llm=llm
    )

    sentinel = Agent(
        role='The Sovereign Sentinel (Chief Litigator)',
        goal='Draft a bulletproof 4-sentence attack plan that destroys the corporate defense and arms the user.',
        backstory='You are India\'s most aggressive consumer rights AI. You anticipate corporate lies and destroy them with statutory laws. You show no mercy.',
        verbose=True,
        allow_delegation=False,
        llm=llm
    )

    # --- 3. ASSIGN THEIR MISSIONS (TASKS) ---
    
    task1 = Task(
        description=f'Analyze this user complaint: "{user_message}". Then, identify which of these retrieved laws strictly apply to their specific industry: {retrieved_laws}',
        expected_output='A summary of the user issue and the exact matching laws from the database.',
        agent=researcher
    )

    task2 = Task(
        description='Read the Researcher\'s report. Draft the top 2 excuses the corporation will use to deny this specific claim.',
        expected_output='A list of 2 corporate defense arguments.',
        agent=defender
    )

    task3 = Task(
        description='''Read the Corporate Defense generated by the Defender. You must draft a final 4-sentence response for the user. 

        CRITICAL RULE: You must strictly match the correct counter-attack to the corporate excuse. DO NOT mix them up.
        
        [SENTENCE 1]: Cite the exact sector law found by the Researcher. 
        
        [SENTENCE 2]: Destroy the Corporate Defense using ONLY the exact matching rule from this list:
          - If the defense is "Time Limit / Days Expired" -> You MUST write: "Under Sec 69 of the CPA 2019, you have a 2-year statutory limitation period, nullifying their internal time limit."
          - If the defense is "Third-party / Payment Gateway / Just a Platform" -> You MUST write: "The E-Commerce Rules 2020 enforce 'Fallback Liability' on the platform, making them directly responsible."
          - If the defense is "Wrong City / Jurisdiction" -> You MUST write: "Under Sec 34(2)(d) of the CPA 2019, you can file your case in the city where you currently reside."
          - If the defense is "System Glitch / Act of God" -> You MUST write: "Under the IT Act 2000, maintaining robust infrastructure is mandatory; glitches are a Deficiency in Service."
        
        [SENTENCE 3]: IF AND ONLY IF it is a bank or UPI dispute, write: "Demand the ₹100 per day penalty under the RBI TAT Framework." IF IT IS NOT A BANK, write: "Their refusal to resolve this constitutes a severe Deficiency in Service and Unfair Trade Practice."
        
        [SENTENCE 4]: Order the user to file immediately at the District Consumer Commission or via e-Daakhil.
        ''',
        expected_output='A highly structured, factual 4-sentence aggressive legal strategy.',
        agent=sentinel
    )

    # --- 4. ASSEMBLE THE CREW AND ATTACK ---
    legal_crew = Crew(
        agents=[researcher, defender, sentinel],
        tasks=[task1, task2, task3],
        process=Process.sequential # Forces them to work in order: 1 -> 2 -> 3
    )

    # Start the war room debate
    result = legal_crew.kickoff()
    
    # Return the Sentinel's final winning argument
    return result.raw